const colors = {
  primary: '#2D9AFF',
  primaryLight: '#198EFA',
  primaryGradientStart: '#51A8F9',
  primaryGradientEnd: '#54CBF6',
  secondaryGradientStart: '#FF3C5E',
  secondaryGradientEnd: '#FF3070',
  profileGradientStart: '#54CBF6',
  profileGradientEnd: '#49D2D0',
  secondary: '#FF4D40',
  secondaryButtonText: '#ffffff',
  primaryButtonText: '#ffffff',
  introText: '#ffffff',
  grey: '#acacac',
  gray: '#5f5f5f',
  darkGray: '#4d4d4d',
  lightGray: '#9b9b9b',
  white: '#ffffff',
  background: '#1E2B5B',
  backgroundLight: '#2D3C72',
  whiteTwo: '#EBEFFB',
  blue: '#5A81F7',
  bluish: '#F1F1F7',
  black: '#000000',
  green: '#6DD0A3',
  yellow: '#ffc247',
  textInputColor: '#ffffff',
  labelOne: '#3CD4A0',
  labelTwo: '#FA7E9D',
};

export default colors;
